import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import imageLoader from '../imageLoader';
import styles from '../styles/Home.module.css'
import { GetCharacterResults,Character } from '../types';




const Home: NextPage<{characters:Character[]}> = ({characters}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
         {/* {JSON.stringify(characters)} */}
         {characters.map((character)=>{
           return(
             <div key={character.id}>

              <Link href={`/characters/${character.id}`} >
                <a> {character.name} </a>
                
              </Link>
            
             </div>
           )
         })}
      
    </div>
  )
}



// baixar alguns dados pra usar nessa pagina, podemos passar como argumento para Home
export const getStaticProps:GetStaticProps = async ()=>{
  //buscar um lista de personagens
   const res = await fetch("https://rickandmortyapi.com/api/character")
   const {results}:GetCharacterResults= await res.json();
  // retorna um objeto com as props, que no nosso caso será os personagens
  console.log('aqui')
   return{
       props:{
           characters:results
       }
   }
  }

export default Home


